services:
  rabbitmq:
    image: rabbitmq:4.2.5-management
    container_name: rabbitmq
    hostname: rabbitmq_node
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin 
      RABBITMQ_DEFAULT_PASS: passwd    
      

  python-pika:
    image: kwonghung/python-pika:latest
    container_name: python-pika
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAIN_PYTHON_FILE=asyncio-conn-2.py
    environment:
      # disable print buffer to so the log
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq