package org.hung.spike.config;

import java.util.UUID;

import org.hung.spike.config.HttpConfiguration.IncomingRequest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.integration.dsl.IntegrationFlow;
import org.springframework.integration.http.dsl.Http;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@Configuration
@Profile("disabled")
public class BarrierExample2 {

    @Bean
    public IntegrationFlow barrierFlow2() {
        return IntegrationFlow
            .from(Http
                .inboundGateway("/barrier2")
                .requestPayloadType(IncomingRequest.class))
            .log()
            .enrichHeaders(spec -> spec.correlationId(UUID.randomUUID()))
            .log()
            .publishSubscribeChannel(pubsub -> {
                pubsub.subscribe(triggerSubflow2());
            })
            // spec.id cannot set the beanName
            .barrier(15 * 1000, spec -> spec.id("abcd1234"))
            .get();
    }

    @Bean
    public IntegrationFlow triggerSubflow2() {
        return IntegrationFlow
            .from("triggerSubflow2.input")
            .log(msg -> "entry trigger subflow...")
            .delay(spec -> spec
                .messageGroupId("test-group-id2")
                .defaultDelay(5 * 1000))
            .log(msg -> "wake up after delay...")
            // The default bean name generated by IntegrationFlow
            .trigger("barrierFlow2.barrier#0")
            .get();
    }
}
