spring:
  application:
    name: agent-response-dispatcher

  docker:
    compose:
      enabled: false
      start:
        command: start
      stop:
        command: stop

  jpa:
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/db1
    username: admin
    password: passwd

  rabbitmq:
    # addresses: amqp://admin:passwd@localhost:5672/
    host: localhost
    port: 5672
    username: admin
    password: passwd

demo:
  rabbitmq:
    outbound:
      exchangeName: agent-request
      queueName: agent-request
      routingKey: agent-request
    inbound:
      exchangeName: agent-response
      queueName: agent-response
      routingKey: agent-response