spring:
  application:
    name: agent-response-dispatcher

  docker:
    compose:
      start:
        command: start
      stop:
        command: stop

  jpa:
    generate-ddl: true

demo:
  rabbitmq:
    outbound:
      exchangeName: agent-request
      queueName: agent-request
      routingKey: agent-request
    inbound:
      exchangeName: agent-response
      queueName: agent-response
      routingKey: agent-response